let isSubmitting = false; const CSRF_TOKEN_URL = '/api/get-csrf-token';
document.addEventListener('DOMContentLoaded', () => { initNavActiveState(); initLazyLoad(); initCsrfToken(); bindMaskedTextEvent(); bindFormSubmitEvent(); initSecureCookie(); });
function initNavActiveState() { try { const currentPath = window.location.hash || '#home'; const activeLink = document.querySelector(.nav-menu a[href=""]); if (activeLink) activeLink.classList.add('active'); } catch (e) { console.error('导航初始化失败:', e); } }
function initLazyLoad() { try { const lazyImgs = document.querySelectorAll('img[data-src]'); if (!lazyImgs.length) return; if ('loading' in HTMLImageElement.prototype) { lazyImgs.forEach(img => img.src = img.dataset.src); return; } if ('IntersectionObserver' in window) { const observer = new IntersectionObserver((entries) => { entries.forEach(entry => { if (entry.isIntersecting) { const img = entry.target; img.src = img.dataset.src; img.removeAttribute('data-src'); observer.unobserve(img); img.onerror = () => { img.alt = '图片加载失败'; img.parentNode.innerHTML = '<div class="img-placeholder">图片加载失败，请稍后重试</div>'; } } }); }); lazyImgs.forEach(img => observer.observe(img)); } } catch (e) { console.error('懒加载失败:', e); const lazyImgs = document.querySelectorAll('img[data-src]'); lazyImgs.forEach(img => img.src = img.dataset.src); } }
function initCsrfToken() { try { fetch(CSRF_TOKEN_URL, { method:'GET', credentials:'same-origin', headers:{'Content-Type':'application/json'} }).then(response => { if (!response.ok) throw new Error('CSRF令牌获取失败'); return response.json(); }).then(data => { const csrfInput = document.querySelector('input[name="csrf_token"]'); if (csrfInput) csrfInput.value = data.token; }).catch(err => { console.error('CSRF令牌异常:', err); isSubmitting = true; alert('安全验证失败，请刷新页面重试'); }); } catch (e) { console.error('CSRF初始化失败:', e); } }
function bindMaskedTextEvent() { try { const maskedText = document.querySelector('.masked-text'); if (maskedText) { maskedText.addEventListener('click', async () => { const isAuthorized = await checkPhoneAuth(); if (isAuthorized) { maskedText.textContent = '19920055453'; maskedText.style.cursor = 'default'; } else { alert('查看完整号码需验证身份，请联系客服'); } }); } } catch (e) { console.error('敏感信息事件绑定失败:', e); } }
async function checkPhoneAuth() { const code = prompt('请输入验证码（示例：1234）:'); return code === '1234'; }
function bindFormSubmitEvent() { try { const orderForm = document.getElementById('order-form'); if (orderForm) { orderForm.addEventListener('submit', (e) => { e.preventDefault(); handleFormSubmit(orderForm); }); } } catch (e) { console.error('表单绑定失败:', e); } }
async function handleFormSubmit(form) { try { if (isSubmitting) { alert("请勿重复提交！"); return; } const agreeCheckbox = form.querySelector('input[name="agree"]'); if (!agreeCheckbox.checked) { alert('请阅读并同意《隐私政策》'); return; } sanitizeFormInputs(form); if (!validateFormInputs(form)) return; setSubmittingState(true); encryptSensitiveFields(form); const formData = new FormData(form); const response = await fetch(form.action, { method:'POST', credentials:'same-origin', body:formData }); const result = await response.json(); if (result.success) { alert('提交成功！我们将尽快与您联系'); form.reset(); } else { alert('提交失败：' + (result.message || '服务器异常')); } } catch (e) { console.error('表单提交失败:', e); alert('提交失败，请稍后重试'); } finally { setTimeout(() => { setSubmittingState(false); }, 5000); } }
function sanitizeFormInputs(form) { try { const inputFields = form.querySelectorAll('input[type="text"], input[type="tel"], input[type="email"], input[type="address"]'); inputFields.forEach(field => { let value = field.value || ''; value = value.replace(/<script.*?>.*?<\/script>/gi, '').replace(/<\/?[^>]*>/gi, '').replace(/&#x[0-9a-f]+;/gi, '').replace(/&#[0-9]+;/gi, '').replace(/['";\\\/<>()%]/g, '').trim(); field.value = value; }); } catch (e) { console.error('输入过滤失败:', e); } }
function validateFormInputs(form) { try { const phone = form.querySelector('#phone').value; const email = form.querySelector('#email').value; const name = form.querySelector('#name').value; const address = form.querySelector('#address').value; const quantity = form.querySelector('#quantity').value; const phoneReg = /^1[3-9]\d{9}$/; if (!phoneReg.test(phone)) { alert("请输入有效的11位手机号！"); return false; } const emailReg = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/; if (!emailReg.test(email)) { alert("请输入有效的邮箱地址！"); return false; } if (!/^[\u4e00-\u9fa5a-zA-Z0-9]{2,20}$/.test(name)) { alert("姓名由2-20个汉字/字母/数字组成，无特殊字符"); return false; } if (address.length > 100 || address.trim() === '') { alert("收货地址不能为空且长度不超过100字符"); return false; } if (quantity < 1 || isNaN(quantity)) { alert("请输入有效的购买数量（至少1件）"); return false; } return true; } catch (e) { console.error('表单验证失败:', e); return false; } }
function encryptSensitiveFields(form) { try { const phone = form.querySelector('#phone'); const email = form.querySelector('#email'); const address = form.querySelector('#address'); } catch (e) { console.error('敏感字段加密失败:', e); } }
function setSubmittingState(isSubmittingFlag) { try { isSubmitting = isSubmittingFlag; const submitBtn = document.getElementById('submitBtn'); if (submitBtn) { submitBtn.disabled = isSubmittingFlag; submitBtn.value = isSubmittingFlag ? '提交中...' : '提交预订'; } } catch (e) { console.error('提交状态设置失败:', e); } }
function initSecureCookie() { try { const sessionId = localStorage.getItem('sessionId') || generateRandomId(); document.cookie = sessionId=; path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=86400; } catch (e) { console.error('Cookie配置失败:', e); } }
function generateRandomId() { return Math.random().toString(36).substring(2,15) + Math.random().toString(36).substring(2,15); }
